# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='password_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('password_size', models.PositiveIntegerField(default=8)),
                ('has_uppercase', models.BooleanField(default=False)),
                ('has_number', models.BooleanField(default=False)),
                ('has_specialchar', models.BooleanField(default=False)),
            ],
        ),
    ]
