# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField(default=8)),
                ('numbers', models.BooleanField(default=True)),
                ('uppers', models.BooleanField(default=True)),
                ('specials', models.BooleanField(default=True)),
            ],
        ),
    ]
